# Generated by Django 3.1.2 on 2020-10-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ArcObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objName', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('curAddress', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=None)),
                ('idType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lvivarc.arctype')),
            ],
        ),
    ]
