# Generated by Django 3.1.2 on 2020-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvivarc', '0002_auto_20201028_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcobj',
            name='imageName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arcobj',
            name='image',
            field=models.ImageField(blank=True, upload_to=models.CharField(blank=True, max_length=100)),
        ),
    ]
