# Generated by Django 3.1.2 on 2020-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvivarc', '0004_auto_20201028_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcobj',
            name='imageName',
        ),
        migrations.AlterField(
            model_name='arcobj',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
