# Generated by Django 3.1.2 on 2020-10-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lvivarc', '0005_auto_20201028_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcobj',
            old_name='idType',
            new_name='objType',
        ),
    ]
